/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.brantapps.slackchannelreader

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun `y'uno write tests`() { }
}
